version: '3'
services:
  front-end:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules

volumes:
  node_modules:
